### ISSUE TITLE
How is the hash being generated?

### ISSUE THREAD

**Issue by sohaibbinmohsin** [faizalshap/react-native-otp-verify#103]
Hello,

Can someone help me understand how the hash is being generated for the app and how I can change it for mine? I want to understand what are the factors that help in generating a unique hash.

Thank you!

**Comment by samroonjesper784758** [comment]
Yes I can surely help you out!

**Comment by samroonjesper784758** [comment]
Yes I can surely help you out!

**Comment by faizalshap** [comment]
Please check the [Google developer guide](https://developers.google.com/identity/sms-retriever/verify)
