### ISSUE TITLE
Not working on Android 14 

### ISSUE THREAD

**Issue by zhekix** [faizalshap/react-native-otp-verify#105]
Hello everyone!

We have updated React Native to version 0.73.2. We are using react-native-otp-verify version 1.1.6. We have noticed that the library has stopped intercepting OTP codes. What could be the reason? Has anyone else encountered this issue before?

Best regards,
Yauheni

**Comment by zhekix** [comment]
Any ideas, maybe tricky workaround ?)

**Comment by ajiehatajie** [comment]
same issue

**Comment by faizalshap** [comment]
I haven't tested recently in the Android 14, 
Anyone has any pointers so far?

**Comment by androideveloper** [comment]
You can patch this line to make it work with android 14.

https://github.com/faizalshap/react-native-otp-verify/blob/07334dedd1ba21c945ae04f977c09ff272591d02/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java#L119

example https://github.com/wix/react-native-navigation/pull/7801/files

**Comment by pgim03** [comment]
Same problem, someone was able to fix it?

**Comment by jerearaujo03** [comment]
[This PR](https://github.com/faizalshap/react-native-otp-verify/pull/106) fix the issue

**Comment by ajiehatajie** [comment]
> [This PR](https://github.com/faizalshap/react-native-otp-verify/pull/106) fix the issue

execellent

**Comment by pgim03** [comment]
> [This PR](https://github.com/faizalshap/react-native-otp-verify/pull/106) fix the issue

In my case I still have a problem, I am working with version 0.72.3 of react native, java 17 and react-native-otp-verfify 1.1.6.

It does not find references to those values.

<img width="710" alt="Captura de pantalla 2024-01-31 a la(s) 10 42 47" src="https://github.com/faizalshap/react-native-otp-verify/assets/61554063/4a1c79e7-80f4-4471-abc5-eeefb28773ae">

<img width="351" alt="Captura de pantalla 2024-01-31 a la(s) 10 43 41" src="https://github.com/faizalshap/react-native-otp-verify/assets/61554063/69e1c409-74d2-4373-83d1-637ec7967bf4">

<img width="438" alt="Captura de pantalla 2024-01-31 a la(s) 10 43 58" src="https://github.com/faizalshap/react-native-otp-verify/assets/61554063/3c54b5c7-cb17-4b86-b9b6-be1faeb80575">

They are being imported from

import android.content.Context;
import android.os.Build;

**Comment by jaraujo-ob** [comment]
I'll take a look

**Comment by jerearaujo03** [comment]
I'll take a look

**Comment by pgim03** [comment]
> I'll take a look

My team and I have come to the conclusion that compileSdkVersion must be modified safeExtGet('OtpVerify_compileSdkVersion', 34) and there it recognizes all the values.

Tests were carried out and it works on Android versions 13 and 14.

In case anyone else has the problem, they can try that.

It would be good to create a PR to fix the root problem.

Thanks for the follow up.

<img width="798" alt="Captura de pantalla 2024-01-31 a la(s) 13 59 17" src="https://github.com/faizalshap/react-native-otp-verify/assets/61554063/90b7794b-51d4-4e8f-b23e-929cab53e87f">

<img width="642" alt="Captura de pantalla 2024-01-31 a la(s) 14 02 32" src="https://github.com/faizalshap/react-native-otp-verify/assets/61554063/698edd9e-e69c-4f67-b2ad-70d39a962639">

**Comment by jerearaujo03** [comment]
Meanwhile you can use this patch:

[react-native-otp-verify+1.1.6.patch](https://github.com/faizalshap/react-native-otp-verify/files/14130353/react-native-otp-verify%2B1.1.6.patch)

**Comment by faizalshap** [comment]
Fixed in v1.1.8
