### ISSUE TITLE
Build error since Feb 16, 2024

### ISSUE THREAD

**Issue by steavenb** [faizalshap/react-native-otp-verify#108]
I am facing a build error with the latest version since Feb 16. The error is as follows:

`Note: Recompile with -Xlint:deprecation for details.
/Users/steavenbc/Documents/codes/ws-mobile/ws-mobile/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java:54: error: cannot find symbol
                .addApi(Auth.CREDENTIALS_API)
                            ^
  symbol:   variable CREDENTIALS_API
  location: class Auth
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-otp-verify:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.`

Tried lowering the version, to 1.1.4 and 1.1.5 too, but it did not work.

**Comment by rvcavalcante-tem** [comment]
having the same issues here

**Comment by jalvarez930** [comment]
Having the sam issue

**Comment by steavenb** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-otp-verify@1.1.6` for the project I'm working on.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
index f500410..040ad6b 100644
--- a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
+++ b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
@@ -51,7 +51,7 @@ public class OtpVerifyModule extends ReactContextBaseJavaModule implements Lifec
         registerReceiverIfNecessary(mReceiver);
         reactContext.addActivityEventListener(this);
         apiClient = new GoogleApiClient.Builder(reactContext)
-                .addApi(Auth.CREDENTIALS_API)
+                .addApi(Auth.GOOGLE_SIGN_IN_API)
                 .build();
     }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by KManiKumarReddy** [comment]
@steavenb even with the patch mentioned the build has been failing -->

> Task :app:compileDevDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
888 actionable tasks: 5 executed, 883 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/mani.kancharla_tho/optimus-ui/apps/mobile/android/app/src/main/java/com/idfcfirstbank/optimus/phoneNumberPicker/PhoneNumberPickerModule.java:20: error: package com.google.android.gms.auth.api.credentials does not exist
import com.google.android.gms.auth.api.credentials.Credential;
                                                  ^
/Users/mani.kancharla_tho/optimus-ui/apps/mobile/android/app/src/main/java/com/idfcfirstbank/optimus/phoneNumberPicker/PhoneNumberPickerModule.java:21: error: package com.google.android.gms.auth.api.credentials does not exist
import com.google.android.gms.auth.api.credentials.HintRequest;
                                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

**Comment by AdityaSinghXenelsoft** [comment]
I am facing same issue .
> Task :react-native-otp-verify:compileDebugJavaWithJavac FAILED
I need help

**Comment by AdityaSinghXenelsoft** [comment]
@steavenb i am getting issue patch-package 7.0.0
• Creating temporary folder
• Installing react-native-otp-verify@1.1.6 with yarn
• Diffing your files with clean files
✔ Created file patches/react-native-otp-verify+1.1.6.patch

node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at module.exports [as default] (E:\React-native\goal\node_modules\open\index.js:175:34) {
  errno: -4064,
  code: 'ENAMETOOLONG',
  syscall: 'spawn'
}

Node.js v20.11.1

Can you help me ?

**Comment by IndrakumarR** [comment]
i'm using  "react-native-otp-verify": "1.1.4",  
I'm also  having this issue

**Comment by KManiKumarReddy** [comment]
@jalvarez930 @steavenb @IndrakumarR @rvcavalcante-tem @AdityaSinghXenelsoft @WooWan 
Another alternative is to set playServiceVersion to 20.7.0 , this library is checking for this value, if it doesn't exist then it's taking the latest.

Latest version for Google Play Services is 21.0.0 which released today and they have removed the deprecated Credentials API -> https://developers.google.com/android/guides/releases

So downgrading to previous version will fix the issue, that is how we've patched the package for now:

```
diff --git a/android/build.gradle b/android/build.gradle
index be64dc0fcbcfaaa813b1d4733baf29df5bbbf339..d717878f34ae6eb03f4c1c65066ae62ca615477e 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -54,7 +54,7 @@ repositories {
 }
 
 dependencies {
-    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '+'))
+    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '20.7.0'))
 
     //noinspection GradleDynamicVersion
     implementation "com.facebook.react:react-native:+"  // From node_modules

```

But then found another alternative which is to set `playServiceVersion` in your root build.gradle ext block like this

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "xxx"
        minSdkVersion = "xx"
        compileSdkVersion = "xx"
        ndkVersion = "xxxx"
        playServiceVersion="20.7.0"
    }
```

**Comment by KManiKumarReddy** [comment]
Maybe we can add a section like this in Readme, if we're planning to support this variable: https://github.com/react-native-maps/react-native-maps/blob/bb0855714895e5264f4f6b3ebc9f3cdc6350b39a/docs/installation.md#build-configuration-on-android

**Comment by faizalshap** [comment]
@KManiKumarReddy if we merge this, i hope it doesn't break existing versions

**Comment by KManiKumarReddy** [comment]
> @KManiKumarReddy if we merge this, i hope it doesn't break existing versions

it'll still break existing versions anyway, we'll either have to upgrade to signin api or set default playservices version to 20.7.0, both will need to publish new version anyways.

Only way existing versions will work is to set that value in gradle file and hope it doesn't cause gradle conflicts

**Comment by shyamaprasadk** [comment]
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🙂
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-otp-verify@1.1.6` for the project I'm working on.
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> index f500410..040ad6b 100644
> --- a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> +++ b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> @@ -51,7 +51,7 @@ public class OtpVerifyModule extends ReactContextBaseJavaModule implements Lifec
>          registerReceiverIfNecessary(mReceiver);
>          reactContext.addActivityEventListener(this);
>          apiClient = new GoogleApiClient.Builder(reactContext)
> -                .addApi(Auth.CREDENTIALS_API)
> +                .addApi(Auth.GOOGLE_SIGN_IN_API)
>                  .build();
>      }
>  
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

It work for me 🥳🥳🥳

**Comment by Saliheen** [comment]
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🙂
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-otp-verify@1.1.6` for the project I'm working on.
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> index f500410..040ad6b 100644
> --- a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> +++ b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> @@ -51,7 +51,7 @@ public class OtpVerifyModule extends ReactContextBaseJavaModule implements Lifec
>          registerReceiverIfNecessary(mReceiver);
>          reactContext.addActivityEventListener(this);
>          apiClient = new GoogleApiClient.Builder(reactContext)
> -                .addApi(Auth.CREDENTIALS_API)
> +                .addApi(Auth.GOOGLE_SIGN_IN_API)
>                  .build();
>      }
>  
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

it works for me

**Comment by AdityaSinghXenelsoft** [comment]
> @jalvarez930 @steavenb @IndrakumarR @rvcavalcante-tem @AdityaSinghXenelsoft @WooWan Another alternative is to set playServiceVersion to 20.7.0 , this library is checking for this value, if it doesn't exist then it's taking the latest.
> 
> Latest version for Google Play Services is 21.0.0 which released today and they have removed the deprecated Credentials API -> https://developers.google.com/android/guides/releases
> 
> So downgrading to previous version will fix the issue, that is how we've patched the package for now:
> 
> ```
> diff --git a/android/build.gradle b/android/build.gradle
> index be64dc0fcbcfaaa813b1d4733baf29df5bbbf339..d717878f34ae6eb03f4c1c65066ae62ca615477e 100644
> --- a/android/build.gradle
> +++ b/android/build.gradle
> @@ -54,7 +54,7 @@ repositories {
>  }
>  
>  dependencies {
> -    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '+'))
> +    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '20.7.0'))
>  
>      //noinspection GradleDynamicVersion
>      implementation "com.facebook.react:react-native:+"  // From node_modules
> ```
> 
> But then found another alternative which is to set `playServiceVersion` in your root build.gradle ext block like this
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "xxx"
>         minSdkVersion = "xx"
>         compileSdkVersion = "xx"
>         ndkVersion = "xxxx"
>         playServiceVersion="20.7.0"
>     }
> ```
> 
> CC: @faizalshap

This worked for me

**Comment by Vikas-EnlitenIT** [comment]
> @jalvarez930 @steavenb @IndrakumarR @rvcavalcante-tem @AdityaSinghXenelsoft @WooWan Another alternative is to set playServiceVersion to 20.7.0 , this library is checking for this value, if it doesn't exist then it's taking the latest.
> 
> Latest version for Google Play Services is 21.0.0 which released today and they have removed the deprecated Credentials API -> https://developers.google.com/android/guides/releases
> 
> So downgrading to previous version will fix the issue, that is how we've patched the package for now:
> 
> ```
> diff --git a/android/build.gradle b/android/build.gradle
> index be64dc0fcbcfaaa813b1d4733baf29df5bbbf339..d717878f34ae6eb03f4c1c65066ae62ca615477e 100644
> --- a/android/build.gradle
> +++ b/android/build.gradle
> @@ -54,7 +54,7 @@ repositories {
>  }
>  
>  dependencies {
> -    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '+'))
> +    def googlePlayServicesVersion = safeExtGet('googlePlayServicesVersion', safeExtGet('playServiceVersion', '20.7.0'))
>  
>      //noinspection GradleDynamicVersion
>      implementation "com.facebook.react:react-native:+"  // From node_modules
> ```
> 
> But then found another alternative which is to set `playServiceVersion` in your root build.gradle ext block like this
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "xxx"
>         minSdkVersion = "xx"
>         compileSdkVersion = "xx"
>         ndkVersion = "xxxx"
>         playServiceVersion="20.7.0"
>     }
> ```
> 
> CC: @faizalshap

This worked for me.

**Comment by navjotsrmtpl** [comment]
Autofilling otp from mobile is not working now startOtpLisner is not able to listen to the events

**Comment by KManiKumarReddy** [comment]
> Autofilling otp from mobile is not working now startOtpLisner is not able to listen to the events

@navjotsrmtpl how did you build the app? did you use the patch-package solution?
Downgrading to `com.google.android.gms:play-services-auth` to 20.7.0 worked for me

**Comment by kuldip-simform** [comment]
Why are we having this issue all of sudden. I am having same issue. Anyone has idea ?

**Comment by KManiKumarReddy** [comment]
> Why are we having this issue all of sudden. I am having same issue. Anyone has idea ?

@kuldip-simform As I've explained in my comment above https://github.com/faizalshap/react-native-otp-verify/issues/108#issuecomment-1947943784, This library is taking the latest version of `com.google.android.gms:play-services-auth` which is upgrading to 21.0.0 and according to release notes https://developers.google.com/android/guides/releases they have removed the CREDENTIALS_API , now why we're using CREDENTIALS_API is a question only authors can answer.

**Comment by technophilix** [comment]
update to version 1.1.18. problem solved.

**Comment by usamaabutt** [comment]
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🙂
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-otp-verify@1.1.6` for the project I'm working on.
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> index f500410..040ad6b 100644
> --- a/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> +++ b/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java
> @@ -51,7 +51,7 @@ public class OtpVerifyModule extends ReactContextBaseJavaModule implements Lifec
>          registerReceiverIfNecessary(mReceiver);
>          reactContext.addActivityEventListener(this);
>          apiClient = new GoogleApiClient.Builder(reactContext)
> -                .addApi(Auth.CREDENTIALS_API)
> +                .addApi(Auth.GOOGLE_SIGN_IN_API)
>                  .build();
>      }
>  
> ```
> 
> _This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296)._

This works for me, and I was using an old version **1.0.5** so I also jumped to the latest version now.

**Comment by AminDannak** [comment]
just upgraded to version 1.1.8 and build was successful

**Comment by paveltar** [comment]
> just upgraded to version 1.1.8 and build was successful

But does the auto otp fill work for you?

**Comment by nguyenanhtuan0799** [comment]
> playServiceVersion="20.7.0"

this works for me 🎉
