### ISSUE TITLE
Not detecting OTP automatically

### ISSUE THREAD

**Issue by mehdihussain9** [faizalshap/react-native-otp-verify#11]
can you provide any full-example with <TextInput> and etc..  I'm confused to where to place that code in my js file

**Comment by abhiburk** [comment]
I have 11 charcter hash code but same issue for me. Not detecting the otp automatically

**Comment by Charmismehta** [comment]
same issue for me got confused with .ts file. can you please provide example in .js file?

**Comment by faizalshap** [comment]
ok cool

**Comment by Tohid1999** [comment]
same

**Comment by Arun-paramasivam** [comment]
Hi guys, I used this package for auto verification of OTP. It works great, but at times its not detecting OTP. Do anyone have any idea of what's causing the problem? I'm stuck at this place for past few days. Any help would be great!

**Comment by sumit-android-haridwar** [comment]
Actually problem is different hashcode for debug and release. when you will compare hashcode of debug and release it will be different

**Comment by Surangaup** [comment]
Please check your play service is up to date. I had the same problem and fixed it by updating the play service.

**Comment by rakeshpangil** [comment]
same issue, have any solution?

**Comment by rukmanary** [comment]
Hi, I have a question. For me, the instruction is not too clear. We can get the hash code from ` getHash()` function right?
So, what's next? The example from @abhiburk shows that we just call ` getHash()` and never use it's return value.

**Comment by hpsurekha** [comment]
You will get 11 characters hash code that you have to use in your text message.

the text message would be like:
**Your 6-digit code: 329769 is valid for 10 minutes
1kTcOHIoaXD**

Note: in the text message, the hash code must be in the next line.

The below code is working fine for me.

```
useEffect(() => {
    this.getHash();
    this.startListeningForOtp();
  },[])

  getHash = () =>
    RNOtpVerify.getHash()
      .then(console.log)
      .catch(console.log);

  startListeningForOtp = () => {
    RNOtpVerify.getOtp()
      .then(p => RNOtpVerify.addListener(this.otpHandler))
      .catch(p => console.log(p));
  }

  otpHandler = (message) => {
    const otp = /(\d{6})/g.exec(message)[1];
    setMatchingOtp(otp);
    RNOtpVerify.removeListener();
    Keyboard.dismiss();
  }
```

**Comment by Rache-lBronfman** [comment]
Is there a way to use this without putting the hash code in the text message?

**Comment by aakashtyagiwmp** [comment]
I used this package to detect the OTP and verify the OTP but it does not detect the OTP only hash is shown.
Please help me!

**Comment by aakashtyagiwmp** [comment]
> Hi guys, I used this package for auto verification of OTP. It works great, but at times its not detecting OTP. Do anyone have any idea of what's causing the problem? I'm stuck at this place for past few days. Any help would be great!

please help me 
I tis not working for me

**Comment by jovanialferez** [comment]
@aakashtyagiwmp  can you share here a snippet of how you implemented it? or a repo probably so people here could help.

**Comment by aakashtyagiwmp** [comment]
> @aakashtyagiwmp can you share here a snippet of how you implemented it? or a repo probably so people here could help.

import RNOtpVerify from 'react-native-otp-verify';

// ****** ComponentDidMount start ****** //
  componentDidMount() {
    if (Platform.OS === 'android') {
      console.log("detect---android");
      this.getHash();
      this.startListeningForOtp();
    }
}
componentWillUnmount() {
    RNOtpVerify.removeListener();
}

 getHash = () => {
  console.log("hash----------------");
  RNOtpVerify.getHash()
    .then(console.log("first------"))
    .catch(console.log("second------------"));
  }

startListeningForOtp = () => {
  console.log("start listen for otp----- start-------");
  RNOtpVerify.getOtp()
    .then(p => RNOtpVerify.addListener(this.otpHandler))
    .catch(p => console.log("function------",p));
}
 otpHandler = (message) => {
        console.log("before otp---------",message);
        const otp = /(\d{6})/g.exec(message)[1];
        console.log("otp0--------",otp);
        this.setState({ otp });
        RNOtpVerify.removeListener();
        Keyboard.dismiss();
}

**Comment by viv3kk** [comment]
I have weird issue.
Otp detect work on builds (apk) but fails on bundles (aab)

@faizalshap

**Comment by AndreiBehel** [comment]
> I have weird issue. Otp detect work on builds (apk) but fails on bundles (aab)
> 
> @faizalshap

Have you found solution for the problem?

**Comment by shailesh-galgal** [comment]
.aab created a different hash key in my case.

**Comment by shailesh-galgal** [comment]
> I have weird issue. Otp detect work on builds (apk) but fails on bundles (aab)
> 
> @faizalshap


.aab created a different hash key in my case.

**Comment by faizalshap** [comment]
@viv3kk  make sure that the Hash is correct
@mehdihussain9  the example is added 
Thanks 👍
