### ISSUE TITLE
Hi all am getting this error below mentioned please let me any solution .

### ISSUE THREAD

**Issue by Mallikarjuna-s** [faizalshap/react-native-otp-verify#111]
/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java:54: error: cannot find symbol
                .addApi(Auth.CREDENTIALS_API)
                            ^
  symbol:   variable CREDENTIALS_API
  location: class Auth
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

/node_modules/react-native-otp-verify/android/src/main/java/com/faizal/OtpVerify/OtpVerifyModule.java:54: error: cannot find symbol
                .addApi(Auth.CREDENTIALS_API)
                            ^
  symbol:   variable CREDENTIALS_API
  location: class Auth
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by faizalshap** [comment]
Hi @Mallikarjuna-s  
Already fixed in latest version - Release 1.1.7

**Comment by Mallikarjuna-s** [comment]
Than you ..
