### ISSUE TITLE
 Error running project compilation

### ISSUE THREAD

**Issue by developer-sistematize** [faizalshap/react-native-otp-verify#112]
![Captura de Tela 2024-02-16 às 11 17 59](https://github.com/faizalshap/react-native-otp-verify/assets/159194626/0d421e9e-bb21-4344-9b14-99eb731f3986)

PACKAGE.JSON
"react-native": "0.71.16",
"react": "18.2.0",
"react-native-otp-verify": "^1.1.6",

**Comment by faizalshap** [comment]
Hi @developer-sistematize  
Fixed in v1.1.7 
Please update to latest version

**Comment by miteshdevg** [comment]
please change .appApi line with below line 
`.addApi(Auth.GOOGLE_SIGN_IN_API)`
