### ISSUE TITLE
Facing error in 1.1.8

### ISSUE THREAD

**Issue by sulaimaan26** [faizalshap/react-native-otp-verify#113]
![image](https://github.com/faizalshap/react-native-otp-verify/assets/49139974/ab782801-56f5-4ccc-813e-a40e2210b8b5)

**Comment by tariksahni** [comment]
+ 1

**Comment by tariksahni** [comment]
Hey @faizalshap 
Can you please help here

**Comment by KManiKumarReddy** [comment]
this shouldn't happen in 1.1.8, there could be some npm/yarn issue, please reinstall the package > 1.1.6 and check the OtpVerifyModule.java in node_modules, it shouldn't contain CREDENTIALS_API

**Comment by sulaimaan26** [comment]
Working fine now Closing this

**Comment by mohdmunaf** [comment]
@sulaimaan26 I am also facing the same issue. How did this solve?
