### ISSUE TITLE
Does it support receiving several messages?

### ISSUE THREAD

**Issue by nikitawolfik** [faizalshap/react-native-otp-verify#12]
I've tried [this](https://github.com/Bruno-Furtado/react-native-sms-retriever) and [this](https://github.com/Rajat421/react-native-sms-retriever-api) libraries, but they both have the following limitation: after receiving the first message with OTP, listener stops working and never reacts to any of the following messages.

What I want is to create a single global listener (in `redux-saga`, for example), listen for every sms with proper hash and then update some part of the state.

So, does the following library has the same limitation as the aforementioned ones?

**Comment by faizalshap** [comment]
I think it should work as long as you don't removeListener
