### ISSUE TITLE
after install and link

### ISSUE THREAD

**Issue by kavindadilshan** [faizalshap/react-native-otp-verify#13]
null is not an object (Evaluating 'RNOtpverify.getotp')

**Comment by faizalshap** [comment]
it means that the library is not linked properly.
Which RN version you are using ?

**Comment by BranescuMihai** [comment]
@faizalshap I have the same problem. RN version: ~0.61.4.  I did the automatic linkage ('Android module "react-native-otp-verify" has been successfully linked') and checked that the manual steps were indeed performed

**Comment by faizalshap** [comment]
Please specify RN version

**Comment by BranescuMihai** [comment]
My project was using expo at that time, that was the problem

**Comment by Basitomania** [comment]
Will automatic linking not work with expo? I'm using expo and encountering the same issue

**Comment by BranescuMihai** [comment]
@Basitomania here's someone from expo explaining it(https://forums.expo.io/t/which-npm-packages-work-with-expo/7830), but essentially, no, this won't work without ejecting from expo

**Comment by pkyad** [comment]
build the app and try again

**Comment by daniel1up** [comment]
@pkyad Does it work with expo after buliding the app?

**Comment by faizalshap** [comment]
Hi this module will not work with expo as it requires native capabilities. You need to eject your app
