### ISSUE TITLE
doesn't support iOS

### ISSUE THREAD

**Issue by gagandeep-s** [faizalshap/react-native-otp-verify#14]
This package doesn't support iOS.

**Comment by edosssa** [comment]
Hi @gagandeep-s, yes it doesn’t and it probably never will. This feature is android specific. If your iOS app uses OTPs, I’d advice you look at [react-native-opt-input](https://github.com/Twotalltotems/react-native-otp-input).

**Comment by faizalshap** [comment]
Yes, it is not supported on iOS
