### ISSUE TITLE
Hash generation

### ISSUE THREAD

**Issue by lakshbhutani** [faizalshap/react-native-otp-verify#20]
Will there be a different hash for debug build and release build and the build(app bundle) uploaded on play store.
If yes how can i create the hash and save it at server end?
Will it be saved at the time when i am sending phone number to get the otp or how?

**Comment by Arun-paramasivam** [comment]
Actually I think ,the hash is generated from the application id ex: com.example.app (bundle id) so it stays the same for each app in debug, release and app bundle if I'm not wrong.

**Comment by sumit-android-haridwar** [comment]
NO it is not same as debug and release

**Comment by jeffelector** [comment]
there is three different hash app id :
1. on debug.
2. when installing the app on device using - npx react-native run-android --variant=release.
3. when installing the app from google play.

You can do this:

 getHash = () =>
        RNOtpVerify.getHash()
            .then(console.log)
            .catch(console.log);

    componentDidMount(): void { 
 if (Platform.OS === "android")
        {
            this.getHash()
            
        }
}

upload a version to google play store,
then you download the app from google play, connect your phone to computer, and run this comment:
react-native log-android
and you will see the app hash for production.

i believe there is a better way .. but this helped me.
i am using web storm.

**Comment by JZorina** [comment]
i uploaded my app to beta in play store - and updated the SMS accordingly - does the hash code will change again once i release to alpha?

**Comment by lakshbhutani** [comment]
> i uploaded my app to beta in play store - and updated the SMS accordingly - does the hash code will change again once i release to alpha?

Yes The hash codes are different for different builds .
When uploading the build in play store the has code will be different.
If you need more help on creating hash please reach out to me at lakshbhutani@gmail.com

**Comment by JZorina** [comment]
the answer is no. the hash wont change when your app is already in internal test track -and you want to upload it to production track on play store

**Comment by faizalshap** [comment]
Please consider reading google docs for this
