### ISSUE TITLE
react-native-otp-verify:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by jitendra-koodo** [faizalshap/react-native-otp-verify#21]
Getting this error while building release version. Same error on Mac and Windows. What could be the reason?

-

> Task :react-native-otp-verify:compileReleaseJavaWithJavac FAILED
E:\app\node_modules\react-native-otp-verify\android\src\main\java\com\faizal\OtpVerify\RNOtpVerifyModule.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
E:\app\node_modules\react-native-otp-verify\android\src\main\java\com\faizal\OtpVerify\RNOtpVerifyModule.java:91: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull
Note: E:\app\node_modules\react-native-otp-verify\android\src\main\java\com\faizal\OtpVerify\AppSignatureHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-otp-verify:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Arun-paramasivam** [comment]
cleaning the build folder did the trick for me!
cd android && ./gradlew clean
from the project root folder

**Comment by GeDiez** [comment]
any updates? 
im running into same issue

**Comment by jmlavoier** [comment]
In order to get rid of this trouble. I've created a fork and fixed this issue in this library. As we can see, this repository is deprecated, it hasn't been maintained. 

I've changed the name to [react-native-otp-autocomplete](https://github.com/jmlavoier/react-native-otp-autocomplete)

The installation and usage are the same, you don't need to change anything. 

```shell
yarn add react-native-otp-autocomplete
```

```js
import OtpAutocomplete from 'react-native-otp-autocomplete';

OtpAutocomplete.getHash().then(() => {}).cathc(() => {});
OtpAutocomplete.getOtp().then(() => {}).cathc(() => {});
OtpAutocomplete.removeListener();
```
You can see the documentation. 

Feel free to create issues and submit some pull requests to maintain the repo.

**Comment by alapanerao** [comment]
I solved it with jetifier. Check below link: [Click Here](https://stackoverflow.com/a/56876517/2512347)

**Comment by amit-soni7** [comment]
> In order to get rid of this trouble. I've created a fork and fixed this issue in this library. As we can see, this repository is deprecated, it hasn't been maintained.
> 
> I've changed the name to [react-native-otp-autocomplete](https://github.com/jmlavoier/react-native-otp-autocomplete)
> 
> The installation and usage are the same, you don't need to change anything.
> 
> ```shell
> yarn add react-native-otp-autocomplete
> ```
> 
> ```js
> import OtpAutocomplete from 'react-native-otp-autocomplete';
> 
> OtpAutocomplete.getHash().then(() => {}).cathc(() => {});
> OtpAutocomplete.getOtp().then(() => {}).cathc(() => {});
> OtpAutocomplete.removeListener();
> ```
> 
> You can see the documentation.
> 
> Feel free to create issues and submit some pull requests to maintain the repo.

This fork worked for me

**Comment by Olixfills** [comment]
> In order to get rid of this trouble. I've created a fork and fixed this issue in this library. As we can see, this repository is deprecated, it hasn't been maintained.
> 
> I've changed the name to [react-native-otp-autocomplete](https://github.com/jmlavoier/react-native-otp-autocomplete)
> 
> The installation and usage are the same, you don't need to change anything.
> 
> ```shell
> yarn add react-native-otp-autocomplete
> ```
> 
> ```js
> import OtpAutocomplete from 'react-native-otp-autocomplete';
> 
> OtpAutocomplete.getHash().then(() => {}).cathc(() => {});
> OtpAutocomplete.getOtp().then(() => {}).cathc(() => {});
> OtpAutocomplete.removeListener();
> ```
> 
> You can see the documentation.
> 
> Feel free to create issues and submit some pull requests to maintain the repo.

This worked for me too
