### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by maihonganh1997** [faizalshap/react-native-otp-verify#22]
As soon as I received the message and it got an error "Cannot read property '1' of null", I debug message = 'Timeout Error.'

**Comment by faizalshap** [comment]
Strange issue. Can you please send the stacktrace ?

**Comment by pruthvirajkarurcodewave** [comment]
Even i am receiving the same error. Where to set the timeout value ?

**Comment by mateodaza** [comment]
same here :( anyone?

**Comment by rukmanary** [comment]
any updates?

**Comment by mohamedadlyy** [comment]
same issue

**Comment by AzranAzwer** [comment]
same issue

**Comment by WaseemAhmed645** [comment]
const otp = /(\d{4})/g.exec(message)[0];

change the [1]. to [0]

**Comment by faizalshap** [comment]
Make sure that you include production hash in the message as stated in the readme.
