### ISSUE TITLE
TypeError: null is not an object (evaluatin 'RNOtpVerify.getOtp')

### ISSUE THREAD

**Issue by student513** [faizalshap/react-native-otp-verify#23]
After installing and linking react-native-otp-verify package into my react-native application when i am trying to run application it showing error:

null is not an object (Evaluating 'RNOtpverify.getOtp')

```
"react-native-otp-verify": "^1.0.3"
"react-native": "0.61.2",
```

I already did ```cd ios && pod install```
How can I solve it?

**Comment by KolyaParadiuk** [comment]
I have the same issue

**Comment by kbihani** [comment]
Even i am seeing the same issue. Works fine on android. Breaks only for ios.

**Comment by webismail92** [comment]
yes I am also getting same error, and my error on android device

**Comment by akshaykumar0291** [comment]
Does anyone get the solution?

**Comment by jp928** [comment]
@student513 
This library seems like works with Android only.

**Comment by ahmadysalah** [comment]
even when I linking I get an error.
![image](https://user-images.githubusercontent.com/44713857/96563637-d61f4780-12ca-11eb-93d8-e2dd2d5d95f9.png)

**Comment by yousefshakoury** [comment]
I had the same issue, but I fixed it by using manual installation then it works correctly!

**Comment by ahmadysalah** [comment]
@yousefshakoury  ist work in ios and android, tell me exactly how u install it manually if u can ..

**Comment by daniel1up** [comment]
I get the same error and I am using expo. Does using expo affect this issue?

**Comment by keremcubuk** [comment]
IOS error has been fixed in this pull request. #32
