### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by PrasathRavichandran** [faizalshap/react-native-otp-verify#24]
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081                                                                                                      ils.
Note: ...\node_modules\react-native-otp-verify\android\src\main\java\com\faizal\OtpVerify\AppSignatureHelper.java uses or overrides a deprecated API.                                                                                                                                                                               
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ... android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ... android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ..\AppData\Roaming\npm-cache\_logs\2020-08-25T08_38_52_244Z-debug.log

while running the react native, the app is not running and throw error

**Comment by faizalshap** [comment]
Will work on it

**Comment by faizalshap** [comment]
Hi @PrasathRavichandran it looks like this issue has nothing to do with the library. Note looks like a warning. Please Correct me if i am wrong

**Comment by PrasathRavichandran** [comment]
Yes, Faizal, it is a warning, it says that the metro server is already running in port 8081. So I am close this ticket. Thank you.
