### ISSUE TITLE
Hash calculation

### ISSUE THREAD

**Issue by khrizt** [faizalshap/react-native-otp-verify#3]
Hi,

This is not an issue, is just a question, I got the hash using your library and it works, but when getting the hash using the commands specified by the SMS retriever API documentation:

`
keytool -exportcert -alias MyAndroidKey -keystore MyProductionKeys.keystore | xxd -p | tr -d "[:space:]" | echo -n com.example.myapp cat | sha256sum | tr -d "[:space:]-" | xxd -r -p | base64 | cut -c1-11
`

The resulting hash is different, is there any particular reason for that?

Thanks

**Comment by faizalshap** [comment]
I am not sure about that. 
The class used to generate hash was mentioned in google repository as example and it works well...

**Comment by khrizt** [comment]
Yes it works, and the one calculated by google command does not (or I made something worng), it was just curiosity, thanks man!!

**Comment by Dror-Bar** [comment]
@khrizt 

I have noticed the same thing. The hash I get from the getHash() method is different than the one I get from google documentation.
However, in my case, using the hash from getHash() did NOT work. I don't think I did anything wrong, I'm using this code:

```
componentDidMount() {
      if (Platform.OS == 'android') {
          RNOtpVerify.getOtp()
              .then(p => RNOtpVerify.addListener(this._handleOTP))
              .catch(p => { });       }
}

_handleOTP(message) {
      // This method is never called when the sms is received
      console.log(message);
}
```

Is there any chance you can share your code? are you doing anything different? how does your sms look like? can you share its' content? (just change the hash).

I will try with the google hash but I will only be able to do so on Sunday and report back.
Thank you very much!

**Comment by khrizt** [comment]
Hey,

Sure, this is my code:

```javascript
if (Platform.OS === 'android') {
  RNOtpVerify.getOtp()
    .then(() => RNOtpVerify.addListener((message) => {
        // do your thing
        RNOtpVerify.removeListener();
      }),
    )
    .catch(() => null);
}
```
And the SMS has to have the following strange and evilish format (yes, that's a line break):

```
<#> [your message]
[HASH]
```
Do you not receive anything or something incorrect?

**Comment by Dror-Bar** [comment]
@khrizt 
Thanks a lot. Your code seems to be basically the same as mine.
In regards to the SMS, I have the same structure, but there are two line breaks instead of one. I don't know if it matters. The SMS reaches my phone but the listener is not receiving anything.

I guess I will try the google hash as well as only one line break and see if it works.
Mind if I ask you one last thing? Did you alter any of the code in node_modules? Also, what version of react-native-otp-verify and react-native are you running?
Thanks a ton, I will update on Sunday if I got this thing working.

**Comment by khrizt** [comment]
The 2 line breaks can be something to fix. This SMS format is very, very strange.

I didn't change anything, make sure you use last version. I'm on 1.0.2 with react-native version 0.57.2 (theoretically you must use >= 0.57.4, but I didn't migrate yet).

Also if you need to do some testing [you can do it in the emulator if you want](https://stackoverflow.com/a/7638361).

**Comment by Dror-Bar** [comment]
I'm also using 1.0.2 but react-native version is 0.55.4. Why would I need version 0.57.4 or above?
Good tip about the SMS emulation. I haven't thought about that.

**Comment by khrizt** [comment]
I don't know exactly but it's defined as peerDependency (so you will only get a warning) for version ^0.57.3 (sorry I get the last one wrong).

**Comment by Dror-Bar** [comment]
@khrizt 
Hey, I figured it out at the end :)
Turns out my message was **too long**, it was literally two words or so above the maximum, which is surprising since it was a rather short message.
Thanks a lot for your help, the tip about sending SMS messages to the emulator helped me debug this quickly.
Have a great day!

**Comment by khrizt** [comment]
Great to hear that!

**Comment by Megha060199** [comment]
@Dror-Bar  What should the maximum word limit be for the message?

**Comment by Dror-Bar** [comment]
@Megha060199 It's not a word limit per se, but simply a size limit. Every character increases the size by a little.
According to [documentation](https://developers.google.com/identity/sms-retriever/verify), the limit is 140 bytes, and it needs to follow a certain structure such as the one they give in their example.

I'd start with this:

```
Your ExampleApp code is: 123ABC78
FA+9qCX9VSu
```

Just change the code at the bottom to your hash.
You might make the message a bit longer but you should really try to keep it to a minimum.

**Comment by Megha060199** [comment]
@Dror-Bar  Thanks :) Last question, does this hash change for debug and release builds? Also, the does the hash code that we get from getHash() work to autoverify

**Comment by Dror-Bar** [comment]
From my experience it can change, but you will have to verify it yourself.
I implemented a special way to trigger an alert with the hash from getHash(), so that I could know for sure what is the current hash (for example, if you submit a specific combination of characters in a TextInput).

**Comment by khrizt** [comment]
It will change between debug and release, and even more generating the release in your machine won't help, you have to publish the app through Google Play to see the real hash. At least that's what I had to do.

**Comment by rukmanary** [comment]
> It will change between debug and release, and even more generating the release in your machine won't help, you have to publish the app through Google Play to see the real hash. At least that's what I had to do.

What if we use `getHash` function from this library and send the value to Server via API? So then if the hash changes, Back End can sent the hash dynamically
