### ISSUE TITLE
Why new requests not released after merge?

### ISSUE THREAD

**Issue by keremcubuk** [faizalshap/react-native-otp-verify#31]
Hello,

I am trying to use react-native-otp-verify in my project but the **androidx** support development not released so that when I trying to pull new package development not reflects. Please decide to standardization of package releases.

I solved the problem temporarily with this way.

`"react-native-otp-verify": "git+https://github.com/faizalshap/react-native-otp-verify.git",`

**Comment by faizalshap** [comment]
Hi @keremcubuk sorry for delay. I will release today :)

**Comment by keremcubuk** [comment]
Thanks @faizalshap
