### ISSUE TITLE
How do I get 11 digit hash key for release version

### ISSUE THREAD

**Issue by AdarshGoswami0335** [faizalshap/react-native-otp-verify#33]
Auto verify is working good and fine in development and when I released the apk auto-verify is not working. I think its a problem of hash key . Can someone tell me how can I get hash key for production . Any help is appreciated

**Comment by Sravansuhas** [comment]
Same here! Any Help.

**Comment by AdarshGoswami0335** [comment]
Yeah I got it

**Comment by Sravansuhas** [comment]
Can you tell me the procedure to resolve this issue?

**Comment by AdarshGoswami0335** [comment]
Yeah sure

**Comment by AdarshGoswami0335** [comment]
Send me a message on whatsapp
+917987273293

**Comment by mohity777** [comment]
Why cant u tell the solution here? Is it  a secret?

**Comment by deepak-jha-kgp** [comment]
Just follow the steps here [Computing your app's hash string](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string)

**Comment by faizalshap** [comment]
@AdarshGoswami0335 the production’s hash differ mostly from development 
so make sure that you are using the right hash key
I will add this in FAQ shortly
