### ISSUE TITLE
_reactNativeOtpVerify.default.getHash is not a function

### ISSUE THREAD

**Issue by saurabhtourtech** [faizalshap/react-native-otp-verify#40]
Getting this issue when try to call RNOtpVerify.getHash().

**Comment by dattv155** [comment]
Same here, when I try to call RNOtpVerify.getOtp()

**Comment by MDAndaya** [comment]
Happens when I call any function from ios, Any idea for any alternative libraries? Especially with Typescript?

**Comment by appsreap** [comment]
Any updates on this bug? Has anyone been able to solve this problem yet?

**Comment by MDAndaya** [comment]
Remove the usage of listenForOtp() and other functions that use otp listener

**Comment by kimsean** [comment]
i am also getting this error.

> Remove the usage of listenForOtp() and other functions that use otp listener
I already removed anything, and just use the function RNOtpVerify.getHash().
but i still gets the same error

**Comment by kimsean** [comment]
any updates on this bug ?

**Comment by blitzve0** [comment]
React Native is Dead and so are all the Packages, Sad for all of us who have running apps on React Native

**Comment by aakash-3990** [comment]
> React Native is Dead and so are all the Packages, Sad for all of us who have running apps on React Native

what is the problem in it

**Comment by blitzve0** [comment]
"react native is dead", is the problem
80% of the packages i use are unmaintained since ages, development experience is garbage I'm tired of packages not working

**Comment by mykeltuz** [comment]
@blitzve0 to be honest when was the last time you donated or sponsored any package, the fault is ours, these packages are built by independent developers like ourselves, but all we do is npm install or yarn add, then we forget to say thank you, what is in it for them. I don't own this repo, I'm just fed up with the way we're just pointing fingers at these guys and forgetting we've got our part to play in keeping React Native alive

**Comment by blitzve0** [comment]
> @blitzve0 to be honest when was the last time you donated or sponsored any package, the fault is ours, these packages are built by independent developers like ourselves, but all we do is npm install or yarn add, then we forget to say thank you, what is in it for them. I don't own this repo, I'm just fed up with the way we're just pointing fingers at these guys and forgetting we've got our part to play in keeping React Native alive

tru i agree donate from my side also

**Comment by arpitBhalla** [comment]
> "react native is dead", is the problem 80% of the packages i use are unmaintained since ages, development experience is garbage I'm tired of packages not working

Maybe because maintainers are human too and very few wants to help them? I have seen React Native Elements library which have 110k+ weekly downloads, still only 2~3 developers took the pain to fix some issue by themselves. maintainers feels burnout, and at the end someone comments _garbage_ for their package. We all expect them to work without paying them, that's the reason many packages are "dead".

I am talking in general, please don't take personally. :)

**Comment by faizalshap** [comment]
Hi, please make sure that the library is properly integrated. and this library is not supported on iOS.

**Comment by Siddhartha-Mukherjee** [comment]
const startListeningForOtp = () =>
    RNOtpVerify.getOtp()
    .then(p => RNOtpVerify.addListener(this.otpHandler))
    .catch(p => console.log(p));

After adding the variable startListeningForOtp, this works.

**Comment by bhuwanadhikari** [comment]
I had to rebuild the app again to make it work. I was giving me error when just restarted metro

**Comment by SanjanaTailor** [comment]
> faizalshap

please let us know this issue facing only in release APK.
