### ISSUE TITLE
ERR! Could not resolve dependency:

### ISSUE THREAD

**Issue by eldirb21** [faizalshap/react-native-otp-verify#41]
npm install react-native-otp-verify --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve 
dependency tree
npm ERR!
npm ERR! While resolving: Andaru_Apps@0.0.1
npm ERR! Found: react-native@0.65.1 
npm ERR! node_modules/react-native  
npm ERR!   react-native@"0.65.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
npm ERR! node_modules/react-native-otp-verify
npm ERR!   react-native-otp-verify@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\eldir\AppData\Local\npm-cache\eresolve-report.txt for a 
full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eldir\AppData\Local\npm-cache\_logs\2021-09-22T12_54_05_206Z-debug.log

How can resolve this problem ?

**Comment by altssolution** [comment]
same error !

**Comment by coderantongmail** [comment]
In RN 0.66.0 has this error

# npm resolution error report

2021-10-05T08:37:11.850Z

While resolving: digitalsnt@0.0.1
Found: react-native@0.66.0
node_modules/react-native
  react-native@"^0.66.0" from the root project

Could not resolve dependency:
peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
node_modules/react-native-otp-verify
  react-native-otp-verify@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react-native",
    "version": "0.66.0",
    "whileInstalling": {
      "name": "digitalsnt",
      "version": "0.0.1",
      "path": "/Volumes/T7 Touch/Development/React-Native/DigitalSNT"
    },
    "location": "node_modules/react-native",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react-native",
        "spec": "^0.66.0",
        "from": {
          "location": "/Volumes/T7 Touch/Development/React-Native/DigitalSNT"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react-native",
    "spec": "^0.66.0",
    "from": {
      "location": "/Volumes/T7 Touch/Development/React-Native/DigitalSNT"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react-native",
    "spec": "^0.63.2",
    "error": "INVALID",
    "from": {
      "name": "react-native-otp-verify",
      "version": "1.0.4",
      "whileInstalling": {
        "name": "digitalsnt",
        "version": "0.0.1",
        "path": "/Volumes/T7 Touch/Development/React-Native/DigitalSNT"
      },
      "location": "node_modules/react-native-otp-verify",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "react-native-otp-verify",
          "spec": "*",
          "from": {
            "location": "/Volumes/T7 Touch/Development/React-Native/DigitalSNT"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}


And cannot upgrade from RN 0.65.1 to 0.66.0

Pleas fix this

**Comment by suhaillilac** [comment]
same issue +1

**Comment by Kajustrevz** [comment]
Same issue +1

**Comment by pushpender-singh-ap** [comment]
Try to install (The latest version is still not published that why you facing this problem)
```
npm i react-native-otp-verify-remastered
```

**Comment by Bilal-Abdeen** [comment]
All of the following issues seem to be about the same problem - dependency on an old version of React-Native. [PR#45](https://github.com/faizalshap/react-native-otp-verify/pull/45) tried to fix the issue by updating the `package.json` file. However, I think `package-lock.json` needs to be updated as well. 

#41, #45 , #56 , #44, #50, #54, #55, #56.
