### ISSUE TITLE
Not able to install this library using npm

### ISSUE THREAD

**Issue by aparnagude396** [faizalshap/react-native-otp-verify#44]
I'm getting this error. I'm using react native version 0.64.1. Can anyone pls look into this issue.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: OTG@0.0.1
npm ERR! Found: react-native@0.64.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
npm ERR! node_modules/react-native-otp-verify
npm ERR!   react-native-otp-verify@"*" from the root project.

**Comment by pushpender-singh-ap** [comment]
Try to install (The latest version is still not published that why you facing this problem)
```
npm install https://github.com/faizalshap/react-native-otp-verify.git
```

**Comment by Bilal-Abdeen** [comment]
All of the following issues seem to be about the same problem - dependency on an old version of React-Native. [PR#45](https://github.com/faizalshap/react-native-otp-verify/pull/45) tried to fix the issue by updating the `package.json` file. However, I think `package-lock.json` needs to be updated as well. 

#41, #45 , #56 , #44, #50, #54, #55, #56.
