### ISSUE TITLE
Get better readme and documentation

### ISSUE THREAD

**Issue by davitdarsalia** [faizalshap/react-native-otp-verify#46]
~  Try to upgrade documentation, which describes every single function more precisely.
~  Adapt your examples for functional components and specify the order of funcs usage.
~ _reactNativeOtpVerify.default.getHash is not a function - Specify, that getHash() can be used if Platform.OS === "android"
~ Specify, that emulator cannot generate otpHash.
~ Show more examples

**Comment by blitzve0** [comment]
React Native is Dead and so are all the Packages, Sad for all of us who have running apps on React Native

**Comment by faizalshap** [comment]
Hi @davitdarsalia 
unfortunately i am having limited time and will try my best to update asap but PRs are most welcome 
Thanks :)
