### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by kashishgrover** [faizalshap/react-native-otp-verify#5]
I tried to integrate this with our React Native project and I got the following error

```
FAILURE: Build failed with an exception.

* Where:
Build file '........................./node_modules/react-native-otp-verify/android/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':react-native-otp-verify'.
> Could not find method google() for arguments [] on repository container.
```

We currently use React Native v0.52 in our app so yeah we are pretty far behind. Does that mean I cannot use this until we upgrade React Native? Are these two things related?

**Comment by Dror-Bar** [comment]
Inside your node_modules folder, find react-native-otp-verify --> android --> build.gradle.
It will look like this:
```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}


...


repositories {
    mavenCentral()
    google()            //   <------ Remove this
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
}

dependencies {
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion
            : project.hasProperty('playServiceVersion') ? project.playServiceVersion : DEFAULT_GOOGLE_PLAY_SERVICES_VERSION
    implementation 'com.facebook.react:react-native:+'
    implementation "com.google.android.gms:play-services-auth:$googlePlayServicesVersion"
}

```

Next, it will probably prompt you about implementation. So change both of those to compile instead.
However, I still don't this will work for you unless you update your build tools to 3.1.4.

**Comment by kashishgrover** [comment]
@Dror-Bar thanks for that, but I still don't think it would work. In the dependencies it uses 'implementation' keyword which is not compatible with our current gradle version. For now, I will simply try and implement the java files of this project in my project as a local dependency. Because we cannot upgrade react native right now, when we do, I will add this back as it is
