### ISSUE TITLE
crash report while installing react-native-otp-verify

### ISSUE THREAD

**Issue by aakashtyagiwmp** [faizalshap/react-native-otp-verify#50]
npm resolution error report

2022-03-10T06:04:20.393Z

While resolving: trakwa-app@2.1.45
Found: react-native@0.64.0
node_modules/react-native
  react-native@"0.64.0" from the root project

Could not resolve dependency:
peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
node_modules/react-native-otp-verify
  react-native-otp-verify@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react-native",
    "version": "0.64.0",
    "whileInstalling": {
      "name": "dummy-App",
      "version": "2.1.45",
      "path": "/home/new/Documents/projects/dummyApp"
    },
    "location": "node_modules/react-native",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react-native",
        "spec": "0.64.0",
        "from": {
          "location":"/home/new/Documents/projects/dummyApp"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react-native",
    "spec": "0.64.0",
    "from": {
      "location": "/home/new/Documents/projects/dummyApp"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react-native",
    "spec": "^0.63.2",
    "error": "INVALID",
    "from": {
      "name": "react-native-otp-verify",
      "version": "1.0.4",
      "whileInstalling": {
        "name": "dummy-App",
        "version": "2.1.45",
        "path": "/home/new/Documents/projects/dummyApp"
      },
      "location": "node_modules/react-native-otp-verify",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "react-native-otp-verify",
          "spec": "*",
          "from": {
            "location": "/home/new/Documents/projects/dummyApp"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}

**Comment by pushpender-singh-ap** [comment]
Try to install (The latest version is still not published that why you facing this problem)
```
npm install https://github.com/faizalshap/react-native-otp-verify.git
```

**Comment by Bilal-Abdeen** [comment]
All of the following issues seem to be about the same problem - dependency on an old version of React-Native. [PR#45](https://github.com/faizalshap/react-native-otp-verify/pull/45) tried to fix the issue by updating the `package.json` file. However, I think `package-lock.json` needs to be updated as well. 

#41, #45 , #56 , #44, #50, #54, #55, #56.
