### ISSUE TITLE
Error when try to install in react-native version 0.67.4

### ISSUE THREAD

**Issue by roysG** [faizalshap/react-native-otp-verify#54]
Roys-MacBook-Pro:app roysabah$ npm install react-native-otp-verify --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@0.0.1
npm ERR! Found: react-native@0.67.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
npm ERR! node_modules/react-native-otp-verify
npm ERR!   react-native-otp-verify@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/roysabah/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roysabah/.npm/_logs/2022-03-24T09_42_31_108Z-debug.log

**Comment by codalprashant** [comment]
Any update on this issue ?

**Comment by roysG** [comment]
Any update?

**Comment by pushpender-singh-ap** [comment]
Try to install (The latest version is still not published that why you facing this problem)
```
npm install https://github.com/faizalshap/react-native-otp-verify.git
```

**Comment by Bilal-Abdeen** [comment]
All of the following issues seem to be about the same problem - dependency on an old version of React-Native. [PR#45](https://github.com/faizalshap/react-native-otp-verify/pull/45) tried to fix the issue by updating the `package.json` file. However, I think `package-lock.json` needs to be updated as well. 

#41, #45 , #56 , #44, #50, #54, #55, #56.
