### ISSUE TITLE
Plugin install issue with RN v0.68

### ISSUE THREAD

**Issue by shridharmanitripathi** [faizalshap/react-native-otp-verify#56]
npm install react-native-otp-verify --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: barika@0.0.1
npm ERR! Found: react-native@0.68.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.68.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.2" from react-native-otp-verify@1.0.4
npm ERR! node_modules/react-native-otp-verify
npm ERR!   react-native-otp-verify@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/otpl/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/otpl/.npm/_logs/2022-04-29T09_18_25_009Z-debug-0.log

**Comment by Bilal-Abdeen** [comment]
All of the following issues seem to be about the same problem - dependency on an old version of React-Native. [PR#45](https://github.com/faizalshap/react-native-otp-verify/pull/45) tried to fix the issue by updating the `package.json` file. However, I think `package-lock.json` needs to be updated as well. 

#41, #45 , #56 , #44, #50, #54, #55, #56.
