### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by e4basil** [faizalshap/react-native-otp-verify#64]
`
   What went wrong:
   Could not determine the dependencies of task ':react-native-otp-verify:verifyReleaseResources'.
> Could not resolve all task dependencies for configuration ':react-native-otp-verify:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-otp-verify
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out
`

**Comment by faizalshap** [comment]
Hi @e4basil 
it seems that jcenter is down today and we are getting 403
For now you can try using the fix here - https://stackoverflow.com/questions/74258160/is-jcenter-down
untill jcenter is up again 
Thanks
