### ISSUE TITLE
error: cannot find symbol com.faizal.OtpVerify.RNOtpVerifyPackage;

### ISSUE THREAD

**Issue by bhavinatharva** [faizalshap/react-native-otp-verify#65]
"react": "16.11.0",
"react-native": "0.61.3"
"react-native-otp-verify": "^1.0.5",
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
supportLibVersion = "28.0.3"

**Comment by faizalshap** [comment]
Hi @bhavinatharva please update to the latest version and try again 
Thanks

**Comment by bhavinatharva** [comment]
Done thank you , please update readme file as well.
