### ISSUE TITLE
Android Build is failing

### ISSUE THREAD

**Issue by kousiclattala** [faizalshap/react-native-otp-verify#66]
**When i build the release apk i get below error.**

<img width="692" alt="Screenshot 2022-11-02 192441" src="https://user-images.githubusercontent.com/51958513/199511581-e073b106-1f23-469a-a0bf-bef5b4872d81.png">

**so i added the configuration mentioned in the package documentation, then i got below error**

<img width="674" alt="Screenshot 2022-11-02 193936" src="https://user-images.githubusercontent.com/51958513/199511778-617a1fa6-f3d3-4c5c-9222-865c7f43cc74.png">

**I have installed the latest version of the package**

"react-native-otp-verify": "^1.1.3",
"react": "18.0.0",
"react-native": "0.69.0",

**Comment by faizalshap** [comment]
You don't need to have that import there @kousiclattala

**Comment by joaofernandesbytepitch** [comment]
Got the same error.

"react-native-otp-verify": "^1.1.4",
"react": "18.0.0",
"react-native": "0.69.6",

Any advice?

**Comment by joaofernandesbytepitch** [comment]
@kousiclattala manually setting sdk version on the build.gradle file did the trick for me.

`android {
    compileSdkVersion safeExtGet('OtpVerify_compileSdkVersion', 31)
    defaultConfig {
        minSdkVersion safeExtGet('OtpVerify_minSdkVersion', 21)
        targetSdkVersion safeExtGet('OtpVerify_targetSdkVersion', 31)
        versionCode 2
        versionName "1.0"

    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    lintOptions {
        disable 'GradleCompatible'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}`

@faizalshap  do you think this can be fixed on my end without the need to update this on the package?

**Comment by faizalshap** [comment]
@kousiclattala what sdk version you are using 
i will check with RN v0.69 
@joaofernandesbytepitch looks like sdk issue to me as well

**Comment by AliYar-Khan** [comment]
Getting error on  "react-native-otp-verify": "^1.0.5",
RN: "react-native": "0.66.5",
 ext.kotlin_version = '1.6.0'
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"

**Comment by LeonardoCalazans** [comment]
Error compile in android
```
Execution failed for task ':react-native-otp-verify:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-otp-verify:debugCompileClasspath'.
   > Could not find com.google.android.gms:play-services-auth:16.1.0.
     Required by:
         project :react-native-otp-verify

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html


```

**Comment by faizalshap** [comment]
@AliYar-Khan  please update to latest version 
@LeonardoCalazans do you have `google()` in your repository section in project level `build.gradle` file?

**Comment by sudeshvs** [comment]
@kousiclattala 


Go to android/app/src/main/java/[...]/MainApplication.java

then remove this line : import com.faizal.OtpVerify.OtpVerifyPackage;

because you are using autoLinking... this line is not needed.. 

one more thing ./gradlew clean

delete node modules and yarn install

happy Coding

**Comment by sudeshvs** [comment]
one more thing 
the otp is not being fetched in an apk generated
anyone facing this issue? please help me...
im lost guys

**Comment by LeonardoCalazans** [comment]
> @AliYar-Khan please update to latest version @LeonardoCalazans do you have `google()` in your repository section in project level `build.gradle` file?

My solution was has to change version `googlePlayServicesVersion = "16.1.0"` to `googlePlayServicesVersion = "20.3.0"`
I need test lib, but build is success.

**Comment by faizalshap** [comment]
Please check if updating the `googlePlayServicesVersion = "16.1.0"` to `googlePlayServicesVersion = "20.3.0"` works ?

**Comment by brunocdeveloper** [comment]
same problem here, should only fix it when they merge the pull that updates the sdk version

**Comment by faizalshap** [comment]
Merged
