### ISSUE TITLE
Works fine in local ,But doesnt work  on apkbuild

### ISSUE THREAD

**Issue by sudeshvs** [faizalshap/react-native-otp-verify#68]
it does not capture the otp from the message
@faizalshap please buddy need help

**Comment by pushpender-singh-ap** [comment]
You should check the key hash after building the apk since the key hash changes when the apk is built.

**Comment by sudeshvs** [comment]
hey how can i get to know the hash key after the apk is build ?

@pushpender-singh-ap

**Comment by faizalshap** [comment]
Yes they are different @sudeshvs 
Run the app in release mode `npx react-native run-android --variant=release`

**Comment by sudeshvs** [comment]
thanks for replying @faizalshap 
i understood what you are saying and how to get the hash... 
ill close the issue once i slove it....
thanks bro @faizalshap

**Comment by pushpender-singh-ap** [comment]
> thanks for replying @faizalshap i understood what you are saying and how to get the hash... ill close the issue once i slove it.... the apk version hash and abb version hash will be same right?? thanks bro @faizalshap

Hash depend on the sign key (keystore) if you don't change it's will same.

**Comment by faizalshap** [comment]
yes correct @pushpender-singh-ap 
@sudeshvs please let me know once you solve this.
I will add this question to FAQ as this is probably one of the most confusing topic in this lib

**Comment by sudeshvs** [comment]
@faizalshap ... i want to know the hash key of my apk ...?
i am not able to console.log the release apk is there a way to get the hash key?

**Comment by pushpender-singh-ap** [comment]
@sudeshvs replace console.log to `alert(`"HASH:- ${hash}`)`

**Comment by sudeshvs** [comment]
thanks @pushpender-singh-ap  ill try it right away

**Comment by pushpender-singh-ap** [comment]
@sudeshvs finally you got the hash key

**Comment by sudeshvs** [comment]
@sudeshvs .. Conclusion

I had Three different hash keys...
1. debug hash key
2. apk release hask key
3. google singing hash key
so people who face this Issue please check your hash key for different builds
i.e 
1.debug,apk and aab.release hash keys

**Comment by sudeshvs** [comment]
@faizalshap buddy my issue is sloved.. thanks bro's @faizalshap @pushpender-singh-ap

**Comment by faizalshap** [comment]
Ok great @sudeshvs 
I will put some way to get the hash more easily and update the readme

**Comment by sudeshvs** [comment]
@faizalshap ...that would be awesome
