### ISSUE TITLE
Automatic sms verification not working for release build

### ISSUE THREAD

**Issue by rishiankush** [faizalshap/react-native-otp-verify#7]
The module is working fine for debug build and I am getting hash properly on msg and it reads the hash automatically too but does not work when I create a release build.

My code:
`getHash = () =>
    RNOtpVerify.getHash()
    .then(console.log)
    .catch(console.log);

    startListeningForOtp = () =>
        RNOtpVerify.getOtp()
        .then((p) => {
            console.log('otp result get ******* ',p)
            RNOtpVerify.addListener(this.otpHandler)
        })
        .catch(p => console.log(p));

    otpHandler = (message: string) => {
        console.log('message ****** ',message)
        let size = message.length;
        let getMessage = message.substring(4,8);
        this.setState({text:getMessage,flag:true},()=>{
            RNOtpVerify.removeListener();
        });
    }
    
    componentDidMount() {
        this.getHash();
        this.startListeningForOtp();
    }`

**Comment by Dror-Bar** [comment]
The hash is different for debug and release builds. Are you sure you are getting and using the correct hash for release mode?

Are you sure the SMS message for release version isn't longer than debug message? the limit is really small. Try to make the message smaller and see if it works.

Are you sure you have in your device, under settings - apps - google play services all permissions enabled?

Finally, if you uploaded to google play store, the hash will once again be different, so you will have to account for that as well.

**Comment by Himvan** [comment]
> The hash is different for debug and release builds. Are you sure you are getting and using the correct hash for release build?
> 
> Are you sure the SMS message for release isn't longer than debug message? The limit is really small. Try to make the message shorter and see if it works.
> 
> Are you sure you have in your device, under settings - apps - google play services, all permissions enabled?
> 
> Try to test with a different device and see if it works.
> 
> Finally, if you uploaded to google play store, the hash will once again be different, so you will have to account for that as well.
> 
> If it's working in debug build, the most likely reason for it not to work in release build is human err.

How can i get the hash fro release build ?

**Comment by shoopi12** [comment]
@Himvan One way is to have a "special" action (such as submitting a specific code in an input) trigger an alert with the hash. I used this trick and it seems perfectly reasonable to me.

**Comment by Himvan** [comment]
and how can i get the hash for google play store ?

**Comment by Himvan** [comment]
> @Himvan One way is to have a "special" action (such as submitting a specific code in an input) trigger an alert with the hash. I used this trick and it seems perfectly reasonable to me.

and how can i get the hash for google play store ?

**Comment by Dror-Bar** [comment]
> > @Himvan One way is to have a "special" action (such as submitting a specific code in an input) trigger an alert with the hash. I used this trick and it seems perfectly reasonable to me.
> 
> and how can i get the hash for google play store ?

After submitting the app to google play store, download it and use the same method to see the hash. Then update your sms accordingly.

**Comment by JZorina** [comment]
if the app is uploaded to the internal test in play store - do the hash code will change after the release to alpha?

**Comment by Dror-Bar** [comment]
I'll be frank with you, I'm not sure. But it's very easy to check if you implement the method mentioned [above](https://github.com/faizalshap/react-native-otp-verify/issues/7#issuecomment-652536150).

**Comment by JZorina** [comment]
yeah - i but i want to be sure before releasing it to alpha

**Comment by JZorina** [comment]
the answer id no. the hash wont change when you release to alpha nor production track on play store

**Comment by Dror-Bar** [comment]
Great.

**Comment by faizalshap** [comment]
i Hope @Dror-Bar has answered all your questions. @Dror-Bar if possible, can you please update the readme.md and raise a PR for this. i will be happy to accept this :)
