### ISSUE TITLE
Regarding Hash: Correct me if I am wrong

### ISSUE THREAD

**Issue by maheshmuttintidev** [faizalshap/react-native-otp-verify#71]
The hash i get in the local dev build can be used in staging and production apks? or will it different for build to build?

**Comment by pushpender-singh-ap** [comment]
Hash depend on the sign key (keystore) if you don't change it's will same.

**Comment by SanjanaTailor** [comment]
@maheshmuttintidev - Facing same issue.

**Comment by SanjanaTailor** [comment]
> Hash depend on the sign key (keystore) if you don't change it's will same.

release unsigned APK itself is throwing an error.

**Comment by pushpender-singh-ap** [comment]
@SanjanaTailor @maheshmuttintidev  try this you will find your key https://github.com/faizalshap/react-native-otp-verify/issues/68#issuecomment-1310622412

Note:- 3 type of keys are generally use so please check your hash key for different builds below some example
1. debug hash key
2. release hask key
3. google singing hash key

**Comment by nizar-mph** [comment]
how to generate release hash key?
