### ISSUE TITLE
Feature Request: Is it possible to implement the OTP verification in iOS devices also?

### ISSUE THREAD

**Issue by maheshmuttinti** [faizalshap/react-native-otp-verify#72]

**Comment by pushpender-singh-ap** [comment]
<TextInput
    ...
    textContentType="oneTimeCode" // ios
/>

Note:- Through this line, iPhone can detect the passcode in Messages and display it above the keyboard. To use the passcode, tap it. You can find more information about autofill OTP at -- [Apple Support](https://support.apple.com/en-in/guide/iphone/iphc89a3a3af/ios) but for now Apple does not support this feature.

**Comment by maheshmuttinti** [comment]
> textContentType="oneTimeCode" // ios

This line of code is independent of the `react-native-otp-verify` package?
