### ISSUE TITLE
When using useOtpVerify hook, retrieved code is always 4 digits length

### ISSUE THREAD

**Issue by mkurczewski** [faizalshap/react-native-otp-verify#79]
There's a bug in `useOtpVerify` hook - `numberOfDigits` parameter is in fact not used at all. Look at line `62` for regex `/(\d{4})/g` - `4` is hardcoded  while there should be `numberOfDigits` variable used, so instead of 

https://github.com/faizalshap/react-native-otp-verify/blob/aff1f30f843144e0910d2fa467028953d36ca7be/src/index.tsx#L62

it should be

```TSX
const regex = new RegExp("(\\d{" + numberOfDigits + "})", "g")
const otpDigits = regex.exec(response)
```

**Comment by VhonaniSpecno** [comment]
this worked for me 
 
` const otp = /(\d{6})/g.exec(message)![1];`

**Comment by khokhas** [comment]
this worked for me

    useEffect(() => {
        startOtpListener(message => {
            if (message) {
                const otp = /(\d{6})/g.exec(message)![1];
                setOTP(otp.split(''));
            }
        });
        return () => removeListener();
    }, []);

**Comment by faizalshap** [comment]
Fixed with PR
