### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by anandrms4u** [faizalshap/react-native-otp-verify#8]
how to integrate this plugin with the react native.
Can provide any demo or example file?

**Comment by faizalshap** [comment]
Hi, i have shown steps in the readme. Did you follow the steps ?
I will include one example as well

**Comment by anandrms4u** [comment]
I just copied your code and put it inside the constructor but it didn't work.
Hope my approach is wrong , kindly tell where to apply code exactly with sample code..
Thanks in advance..

**Comment by codemeall** [comment]
@anandrms4u did you make it work, @faizalshap can you please provide an example for how to add the listner in the component? 

thanks

**Comment by faizalshap** [comment]
Sure, will be updating this library soon

**Comment by faizalshap** [comment]
Example added 👍
