### ISSUE TITLE
Hash key updated confusion.

### ISSUE THREAD

**Issue by DivyeshPonkiya** [faizalshap/react-native-otp-verify#80]
application already publish on play store. but some day after updated abb upload on playstore  this time HASH key (11 digit key) in any changes?

**Comment by nizar-mph** [comment]
How did you generated HASH key, could you please help me once?

**Comment by ridvanaltun** [comment]
> application already publish on play store. but some day after updated abb upload on playstore this time HASH key (11 digit key) in any changes?

According to Google document answer is no. 

> Google Play services uses the hash string to determine which verification messages to send to your app. The hash string is made of your app's package name and your app's public key certificate.

---

> How did you generated HASH key, could you please help me once?

Check here https://developers.google.com/identity/sms-retriever/verify?hl=en#computing_your_apps_hash_string
