### ISSUE TITLE
Execution failed for task ':react-native-otp-verify:verifyReleaseResources'.

### ISSUE THREAD

**Issue by brunocdeveloper** [faizalshap/react-native-otp-verify#84]
I have the following error and I don't know how to proceed, I've seen some solutions about changing the build.gradlew of the lib directly in node_modules, but this is not an alternative since I need to upload the project.

I saw some suggestions pointing the problem as a difference in the sdk version of the lib and the project.

Has anyone experienced this and know how to resolve it?
Any way to get around the problem?

![image](https://user-images.githubusercontent.com/72170223/221375198-366d3316-6af7-4751-8629-cab720c7a7fb.png)

**Comment by mohammad6vakili** [comment]
same issue!

**Comment by shahanshah87** [comment]
@faizalshap any update on this?

**Comment by faizalshap** [comment]
Hi Guys, will give a check on this.
Can you please let me know your version of build gradle and react native
Thanks

**Comment by shahanshah-cutshort** [comment]
```
// ./gradlew --version
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.17 (Azul Systems, Inc. 11.0.17+8-LTS)
OS:           Mac OS X 13.3 aarch64`

//react native
"react-native": "0.70.5"

 android/build.gradle
classpath("com.android.tools.build:gradle:7.2.1")

**Comment by shahanshah-cutshort** [comment]
```
// ./gradlew --version
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
OS:           Mac OS X 13.3 aarch64`

//react native
"react-native": "0.70.5"

 android/build.gradle
classpath("com.android.tools.build:gradle:7.2.1")

**Comment by DinoZenka** [comment]
same issue when run in dev/build app. Also, if use './gradlew app:assembleRelease' instead of './gradlew assembleRelease', then app is built successfully. But still don't know how to run in dev mode.

Output of _./gradlew --version_

Gradle 7.5.1

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.16.1 (Oracle Corporation 11.0.16.1+1-LTS-1)
OS:           Mac OS X 12.6.1 aarch64


Output of _npx react-native info_

System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 102.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/maksym/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by OtavioStasiak** [comment]
Hi guys! How is it going?
I had this problem and I solve it upgrading the target SDK version on "node_modules/react-native-otp-verify/android/build.gradle"

change the line 22 and 25 to sdk 31:
`
android {
    compileSdkVersion safeExtGet('OtpVerify_compileSdkVersion', 31)
    defaultConfig {
        minSdkVersion safeExtGet('OtpVerify_minSdkVersion', 16)
        targetSdkVersion safeExtGet('OtpVerify_targetSdkVersion', 31)
        versionCode 2
        versionName "1.0"
    }
`

I hope that this solution can help you.
Greetings.

**Comment by faizalshap** [comment]
Fixed with PR
