### ISSUE TITLE
How to pass the hash to Firebase methods?

### ISSUE THREAD

**Issue by Bilal-Abdeen** [faizalshap/react-native-otp-verify#85]
I use Firebase authentication. Firebase generates the OTP and sends it to the user's device. How can I pass the hash value generated by react-native-otp-verify to Firebase? Following is the Firebase method I use. 
```javascript
firebase.auth().signInWithPhoneNumber(phoneNo).then();
```

**Comment by faizalshap** [comment]
Hi Bilal,
Firebase already has this implemented internally so you don't need this
library.

**Comment by Bilal-Abdeen** [comment]
@faizalshap Thank you very much for the super quick reply. I am struggling to get it to work. I have just asked a question on react-native-firebase GitHub page [https://github.com/invertase/react-native-firebase/discussions/6950](https://github.com/invertase/react-native-firebase/discussions/6950). Hopefully, someone would help me there.

**Comment by faizalshap** [comment]
ok cool
