### ISSUE TITLE
on manual link how to add this

### ISSUE THREAD

**Issue by hassanharoon321** [faizalshap/react-native-otp-verify#87]
Add new OtpVerifyPackage() to the list returned by the getPackages() method

**Comment by mo-nizar** [comment]
go to app/src/main/java/.../MainApplication.java
scroll down and find getPackages() method
 
it looks something like this:

protected List<ReactPackage> getPackages() {

      // Default React Native Packages

      List<ReactPackage> reactPackageList = new ArrayList<>(Arrays.asList(
      ....
      ....

after:

  protected List<ReactPackage> getPackages() {
  
        // Default React Native Packages
  
        List<ReactPackage> reactPackageList = new ArrayList<>(Arrays.asList(
             new OtpVerifyPackage()
